name: Docker CI

on: workflow_dispatch

permissions:
  contents: write

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules init
        run: git submodule init
      - name: Checkout submodules update
        run: git submodule update --remote
      - name: Copy overlays
        run: cp -n -R fedora-coreos-config/overlay.d .
      - name: Pwd
        run: pwd
      - name: Disk free before
        run: df -h
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Disk free after
        run: df -h
      - name: Build Docker image
        run: docker build . -t localhost/coreos
      - name: Copy distro
        run: docker cp $(docker create localhost/coreos):/srv/target/. ./target
#      - name: Remove iso from publishing
#        run: rm ./target/*.iso
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*"
          body: "Custom coreos build (v37 base)"
          tag: "v1.0.2"
