name: Docker CI

on: workflow_dispatch

permissions:
  contents: write

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodukes
        run: git submodule update --init --recursive
      - name: Cleanup target
        run: rm ./target/dummy
      - name: Build Docker image
        run: docker build . -t localhost/coreos
      - name: Copy distro
        run: docker cp $(docker create localhost/coreos):/srv/target/. ./target
      - name: Remove iso from publishing
        run: rm ./target/*.iso
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*"
          body: "Custom coreos build (v37 base)"
          tag: "v1.0.1"
